apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-page
  template:
    metadata:
      labels:
        app: web-page
    spec:
      containers:
        - name: web-page
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80

          # livenessProbe – kontrola či proces žije (ak nie, reštart)
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}

          # readinessProbe – či je pod pripravený prijímať traffic (Service)
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
            successThreshold: {{ .Values.probes.successThreshold }}

          # startupProbe – čas na štart (pri väčších appkách)
          startupProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.probes.port }}
            failureThreshold: 30
            periodSeconds: 5

          resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | nindent 12 }}
{{- end }}

          volumeMounts:
{{- if .Values.storage.enabled }}
            - name: web-page-data
              mountPath: /usr/share/nginx/html
{{- end }}

      volumes:
{{- if .Values.storage.enabled }}
        - name: web-page-data
          persistentVolumeClaim:
            claimName: web-page-pvc
{{- end }}
